course = 'mooc-java-programming-ii'
[exercises."part08-Part08_01.Cubes"]
id = 87694
checksum = '43758bf10ed212527b17b958a74534c5'

[exercises."part08-Part08_02.AverageOfPositiveNumbers"]
id = 87695
checksum = '9e2ae6b3c65b63f4af0ebe4c60544263'

[exercises."part08-Part08_03.LiquidContainers"]
id = 87696
checksum = 'a57aa15e265e63a26f92442ca171591a'

[exercises."part08-Part08_04.LiquidContainers2"]
id = 87697
checksum = '4e2451f336269dabd492e2d2e3ebcd95'

[exercises."part08-Part08_05.TodoList"]
id = 87698
checksum = '04722994ee2124b19bc4381c74b3b391'

[exercises."part08-Part08_06.Nicknames"]
id = 87699
checksum = '1da57b943422048473e20eee1f0ca80d'

[exercises."part08-Part08_07.Abbreviations"]
id = 87700
checksum = '85e992b573e26c8f7a9f702e946299da'

[exercises."part08-Part08_08.PrintMeMyHashmap"]
id = 87701
checksum = '8f3fe76736082ba14ea9020c09bee243'

[exercises."part08-Part08_09.PrintMeAnotherHashmap"]
id = 87702
checksum = '65bdf1f4f19aa3ccf62032b79f9f6632'

[exercises."part08-Part08_10.IOweYou"]
id = 87703
checksum = '31c32815ce2e698d992dc54a8ad2c134'

[exercises."part08-Part08_11.SameDate"]
id = 87704
checksum = 'a1e43d456c4faa798a4c85d1fa14a2e8'

[exercises."part08-Part08_12.HashedDate"]
id = 87705
checksum = 'd2f8918218e9ca49f1cefca3154ecef5'

[exercises."part08-Part08_13.VehicleRegistry"]
id = 87706
checksum = '0c3417697743a379ea4def4e895841c8'

[exercises."part08-Part08_14.DictionaryOfManyTranslations"]
id = 87707
checksum = '1c20b8c8f052fa3b6a6b67f3126716e9'

[exercises."part08-Part08_15.StorageFacility"]
id = 87708
checksum = 'd2750f7633eb16c5cab867530685d3cf'

[exercises."part09-Part09_01.ABC"]
id = 87709
checksum = '33cc80381376403e8c0c6e8f342acf9f'

[exercises."part09-Part09_02.PersonAndSubclasses"]
id = 87710
checksum = 'dcade1c7820051848ded94edd9c661a3'

[exercises."part09-Part09_03.Warehousing"]
id = 87711
checksum = '27a785b46714b5314e3d576bfb4761d3'

[exercises."part09-Part09_04.DifferentKindsOfBoxes"]
id = 87712
checksum = 'd4cff1c1edda8c017d1d40aa7e72c3d4'

[exercises."part09-Part09_05.TacoBoxes"]
id = 87713
checksum = 'b1ff116697db764e64120ddf4c91aacc'

[exercises."part09-Part09_06.InterfaceInABox"]
id = 87714
checksum = 'ec453cc8e80c08653432bd8463b0e485'

[exercises."part09-Part09_07.ListAsAMethodParameter"]
id = 87715
checksum = '85880b47dc57a786b351680ab2a01065'

[exercises."part09-Part09_08.MapAsAMethodParameter"]
id = 87716
checksum = '224e189c39407fd9ea1f2ab26f430040'

[exercises."part09-Part09_09.SetAsMethodParameter"]
id = 87717
checksum = 'd7ce961b6f1fd94904d87522cbf71259'

[exercises."part09-Part09_10.OnlineShop"]
id = 87718
checksum = '46afb3cfc5458af4432cd209d67003a0'

[exercises."part09-Part09_11.Herds"]
id = 87719
checksum = '429d7525f586e32887cb08dbd8070e8c'

[exercises."part09-Part09_12.Animals"]
id = 87720
checksum = 'd5fc386695a60979fb147901032fa700'

[exercises."part10-Part10_01.AverageOfNumbers"]
id = 87721
checksum = '270ec217fcc94e087869496574f20362'

[exercises."part10-Part10_02.AverageOfSelectedNumbers"]
id = 87722
checksum = '246d1456df9a708383bf1752bac64a9e'

[exercises."part10-Part10_03.PositiveNumbers"]
id = 87723
checksum = '66c146233423aeb35d12cf5a2d773b22'

[exercises."part10-Part10_04.Divisible"]
id = 87724
checksum = '6d5d14ee5216156e81a36daf56b49d20'

[exercises."part10-Part10_05.PrintingUserInput"]
id = 87725
checksum = 'c99ae3028a776f6b886774b88896f3b9'

[exercises."part10-Part10_06.LimitedNumbers"]
id = 87726
checksum = '79e733bc51ec7ee849a276c7dd332b2d'

[exercises."part10-Part10_07.UniqueLastNames"]
id = 87727
checksum = '0acb395be532c59ac831c8b3fffcc48e'

[exercises."part10-Part10_08.Weighting"]
id = 87728
checksum = '80b2f77b4cd6dd9352293c00f9d99c7c'

[exercises."part10-Part10_09.ReadingFilesPerLine"]
id = 87729
checksum = '9dd063845b3a512271c20320cc128e7f'

[exercises."part10-Part10_10.BooksFromFile"]
id = 87730
checksum = '23d7d097731a3815d3d9b8ee24c8738d'

[exercises."part10-Part10_11.WageOrder"]
id = 87731
checksum = '08635d3cffb24afd01ff1780cd77bc65'

[exercises."part10-Part10_12.StudentsOnAlphabeticalOrder"]
id = 87732
checksum = '1a9f62c3b66e534e90c080494ef455f0'

[exercises."part10-Part10_13.LiteracyComparison"]
id = 87733
checksum = 'bf9068417b42d845318ef8da69d18961'

[exercises."part10-Part10_14.Literature"]
id = 87734
checksum = '80151db58eb4bcc3c8b628c607d0a601'

[exercises."part10-Part10_15.RegularExpressions"]
id = 87735
checksum = '5ba873d3c696dd24767fbef24227ec85'

[exercises."part10-Part10_16.EnumAndIterator"]
id = 87736
checksum = 'cef95ad12b7acbf366ac1b6c0835a531'

[exercises."part10-Part10_17.SortThemCards"]
id = 87737
checksum = 'e547c245001554fe16126a4159c38d54'
